
default:
	gcc	-O0 -o 2.exe 2.c
	./2.exe

debug:
	gcc -o 2.exe 2.c -O0 -ggdb -m32
	gdb -q 2.exe

0:
	gcc	-O0 -o 2.exe 2.c
	./2.exe 0

1:
	gcc	-O0 -o 2.exe 2.c
	./2.exe 1

2:
	gcc	-O0 -o 2.exe 2.c
	./2.exe 2